# Generated by Django 3.1.1 on 2020-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InputOutput', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docmas',
            name='filePath',
        ),
        migrations.RemoveField(
            model_name='docmas',
            name='origFileName',
        ),
        migrations.AddField(
            model_name='docmas',
            name='file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
