# Generated by Django 3.1.1 on 2020-10-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InputOutput', '0003_remove_docmas_docid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docmas',
            name='file',
        ),
        migrations.AddField(
            model_name='docmas',
            name='docId',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docmas',
            name='filePath',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docmas',
            name='origFileName',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
