# Generated by Django 3.1.1 on 2020-10-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InputOutput', '0004_auto_20201001_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='digitizeDtls',
        ),
        migrations.AddField(
            model_name='docmas',
            name='status',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docmas',
            name='userId',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
