# Generated by Django 3.1.1 on 2020-10-01 14:44

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('InputOutput', '0006_docdtls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docdtls',
            name='optional',
        ),
        migrations.AddField(
            model_name='docdtls',
            name='GST',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docdtls',
            name='additional',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docdtls',
            name='invoiceNumber',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docdtls',
            name='items',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docdtls',
            name='paymentInfo',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docdtls',
            name='paymentStatus',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docdtls',
            name='seller',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docdtls',
            name='shipTo',
            field=jsonfield.fields.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docdtls',
            name='totalPrice',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docdtls',
            name='buyer',
            field=models.CharField(max_length=500),
        ),
    ]
