# Generated by Django 3.1.1 on 2020-10-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InputOutput', '0007_auto_20201001_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pwd',
            new_name='psswd',
        ),
    ]
